swagger: "2.0"
basePath: /
host: users
info:
  version: 0.0.1
  title: Swagger template
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /users:
    post:
      tags: ["users"]
      operationId: createUser
      summary: Creates user
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/user"
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/user"
        "500":
          description: Internal error
          schema:
            $ref: "#/definitions/error"
    put:
      tags: ["users"]
      operationId: updateUser
      summary: Updates user
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/user"
      responses:
        "200":
          description: Updated
          schema:
            $ref: "#/definitions/user"
        "404":
          description: Not found error
          schema:
            $ref: "#/definitions/error"
        "500":
          description: Internal error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags: ["main_service"]
      operationId: deleteUser
      summary: Deletes user
      parameters:
        - name: body
          in: body
          schema:
            type: object
            required:
              - userId
            properties:
              userId:
                type: string
                format: uuid
      responses:
        "204":
          description: Deleted
        "404":
          description: Not found error
          schema:
            $ref: "#/definitions/error"
        "500":
          description: Internal error
          schema:
            $ref: "#/definitions/error"
definitions:
  user:
    type: object
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      email:
        type: string
        format: email
  error:
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
